"""empty message

Revision ID: 00b457e70388
Revises: 9c6eebe99064
Create Date: 2021-04-17 21:21:47.113655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b457e70388'
down_revision = '9c6eebe99064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cars_model_user_id_fkey', 'cars_model', type_='foreignkey')
    op.create_foreign_key(None, 'cars_model', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('favourites_car_id_fkey', 'favourites', type_='foreignkey')
    op.drop_constraint('favourites_user_id_fkey', 'favourites', type_='foreignkey')
    op.create_foreign_key(None, 'favourites', 'cars_model', ['car_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favourites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favourites', type_='foreignkey')
    op.drop_constraint(None, 'favourites', type_='foreignkey')
    op.create_foreign_key('favourites_user_id_fkey', 'favourites', 'users', ['user_id'], ['id'])
    op.create_foreign_key('favourites_car_id_fkey', 'favourites', 'cars_model', ['car_id'], ['id'])
    op.drop_constraint(None, 'cars_model', type_='foreignkey')
    op.create_foreign_key('cars_model_user_id_fkey', 'cars_model', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
