"""empty message

Revision ID: 9c6eebe99064
Revises: f79f423de203
Create Date: 2021-04-17 21:03:53.395678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6eebe99064'
down_revision = 'f79f423de203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cars_model', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars_model', type_='foreignkey')
    # ### end Alembic commands ###
