"""empty message

Revision ID: ad9c64efcbd3
Revises: 00b457e70388
Create Date: 2021-04-17 21:36:22.265098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9c64efcbd3'
down_revision = '00b457e70388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars_model', sa.Column('colour', sa.String(length=160), nullable=True))
    op.drop_column('cars_model', 'color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars_model', sa.Column('color', sa.VARCHAR(length=160), autoincrement=False, nullable=True))
    op.drop_column('cars_model', 'colour')
    # ### end Alembic commands ###
